project:
  type: website
  output-dir: docs

website:
  title: "Advanced Machine Learning with Python workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: notes/DL_image_analysis_1.qmd
        text: Session 1
      - href: notes/DL_image_analysis_2_1.qmd
        text: Session 2 - Part 1
      - href: notes/DL_image_analysis_2_2.qmd
        text: Session 2 - Part 2
      - href: notes/DL_image_analysis_2_3.qmd
        text: Session 2 - Part 3

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    self-contained: true
